server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].exposedHeaders=Authorization,X-Correlation-ID

# Gateway Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=profile-service
spring.cloud.gateway.routes[1].uri=lb://profile-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/profiles/**

spring.cloud.gateway.routes[2].id=product-service
spring.cloud.gateway.routes[2].uri=lb://product-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/products/**

spring.cloud.gateway.routes[3].id=cart-service
spring.cloud.gateway.routes[3].uri=lb://cart-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/cart/**

spring.cloud.gateway.routes[4].id=inventory-service
spring.cloud.gateway.routes[4].uri=lb://inventory-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/inventory/**

spring.cloud.gateway.routes[5].id=order-service
spring.cloud.gateway.routes[5].uri=lb://order-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.routes[6].id=wallet-service
spring.cloud.gateway.routes[6].uri=lb://wallet-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/wallet/**

spring.cloud.gateway.routes[7].id=payment-service
spring.cloud.gateway.routes[7].uri=lb://payment-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/payments/**

spring.cloud.gateway.routes[8].id=delivery-service
spring.cloud.gateway.routes[8].uri=lb://delivery-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/delivery/**

spring.cloud.gateway.routes[9].id=notification-service
spring.cloud.gateway.routes[9].uri=lb://notification-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/notifications/**

spring.cloud.gateway.routes[10].id=review-service
spring.cloud.gateway.routes[10].uri=lb://review-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/reviews/**

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,metrics
